### ISSUE TITLE
Error When Opening App Preferences

### ISSUE THREAD

**Issue by kevmarsden** [Automattic/wp-desktop#218]
When opening Preferences from the WordPress.com menu, the following error appears in a new window:

> WordPress.com ran into an error
> 
> Please restart the app and try again.
> 
> If you continue to have issues, please contact us at help@wordpress.com and mention the error details below:
> 
> Error: Cannot find module '../screen'
>     at Module._resolveFilename (module.js:438:15)
>     at Function.Module._resolveFilename (/Applications/WordPress.app/Contents/Resources/electron.asar/common/reset-search-paths.js:47:12)
>     at Function.Module._load (module.js:386:25)
>     at Module.require (module.js:466:17)
>     at require (internal/module.js:20:19)
>     at Object.defineProperties.screen.get [as screen] (/Applications/WordPress.app/Contents/Resources/electron.asar/browser/api/exports/electron.js:83:14)
>     at setDimensions (/Applications/WordPress.app/Contents/Resources/app/desktop.js:30316:26)
>     at openWindow (/Applications/WordPress.app/Contents/Resources/app/desktop.js:30332:31)
>     at Object.module.exports.openPreferences (/Applications/WordPress.app/Contents/Resources/app/desktop.js:30351:4)
>     at menuItems.click (/Applications/WordPress.app/Contents/Resources/app/desktop.js:148000:19)
> 
> System info: {"platform":"darwin","release":"15.6.0","version":"1.4.0-beta1","build":"release"}

Preferences opens correctly once the app restarts.  If the WordPress app is closed and reopened, the error appears again.  

Originally reported in ticket 2760291-t.

**Comment by rachelmcr** [comment]
I was getting the same error using version 1.4.0-beta1 and the new 1.5.0-beta1 release, on Mac OS X 10.11.5. However, I just updated to Mac OS X 10.11.6 and the error was resolved. (I can now load the About WordPress.com and Preferences screens without any issue.)

**Comment by daveti** [comment]
Error: Cannot find module '../screen'
    at Module._resolveFilename (module.js:438:15)
    at Function.Module._resolveFilename (/Applications/WordPress.com.app/Contents/Resources/electron.asar/common/reset-search-paths.js:47:12)
    at Function.Module._load (module.js:386:25)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.defineProperties.screen.get [as screen] (/Applications/WordPress.com.app/Contents/Resources/electron.asar/browser/api/exports/electron.js:83:14)
    at setDimensions (/Applications/WordPress.com.app/Contents/Resources/app/desktop.js:30316:26)
    at openWindow (/Applications/WordPress.com.app/Contents/Resources/app/desktop.js:30332:31)
    at Object.module.exports.openAbout (/Applications/WordPress.com.app/Contents/Resources/app/desktop.js:30354:4)
    at menuItems.splice.click (/Applications/WordPress.com.app/Contents/Resources/app/desktop.js:148050:20)

System info: {"platform":"darwin","release":"15.6.0","version":"1.4.0","build":"release"}

**Comment by kevmarsden** [comment]
On Mac OSX 10.11.6 with the 1.5.0-beta1 release, I'm still getting the error intermittently

> Error: Cannot find module '../screen'
>     at Module._resolveFilename (module.js:438:15)
>     at Function.Module._resolveFilename (/Applications/WordPress.app/Contents/Resources/electron.asar/common/reset-search-paths.js:47:12)
>     at Function.Module._load (module.js:386:25)
>     at Module.require (module.js:466:17)
>     at require (internal/module.js:20:19)
>     at Object.defineProperties.screen.get [as screen] (/Applications/WordPress.app/Contents/Resources/electron.asar/browser/api/exports/electron.js:83:14)
>     at setDimensions (/Applications/WordPress.app/Contents/Resources/app/desktop.js:30417:26)
>     at openWindow (/Applications/WordPress.app/Contents/Resources/app/desktop.js:30433:31)
>     at Object.module.exports.openPreferences (/Applications/WordPress.app/Contents/Resources/app/desktop.js:30452:4)
>     at menuItems.click (/Applications/WordPress.app/Contents/Resources/app/desktop.js:148196:19)
> 
> System info: {"platform":"darwin","release":"15.6.0","version":"1.5.0-beta1","build":"release"}

**Comment by rachelmcr** [comment]
Well, darn. It's back for me now, too (with no changes I can think of on my part). I get the same error any time I open the Preferences menu.

I also get this error any time I open the About WordPress.com menu:

> Error: Cannot find module '../screen'
    at Module._resolveFilename (module.js:438:15)
    at Function.Module._resolveFilename (/Applications/WordPress.com.app/Contents/Resources/electron.asar/common/reset-search-paths.js:47:12)
    at Function.Module._load (module.js:386:25)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.defineProperties.screen.get [as screen] (/Applications/WordPress.com.app/Contents/Resources/electron.asar/browser/api/exports/electron.js:83:14)
    at setDimensions (/Applications/WordPress.com.app/Contents/Resources/app/desktop.js:30417:26)
    at openWindow (/Applications/WordPress.com.app/Contents/Resources/app/desktop.js:30433:31)
    at Object.module.exports.openAbout (/Applications/WordPress.com.app/Contents/Resources/app/desktop.js:30455:4)
    at menuItems.splice.click (/Applications/WordPress.com.app/Contents/Resources/app/desktop.js:148246:20)

> System info: {"platform":"darwin","release":"15.6.0","version":"1.5.0-beta1","build":"release"}

cc @sendhil

**Comment by sendhil** [comment]
Thanks for the heads up @rachelmcr - will investigate.

**Comment by sendhil** [comment]
I have a fix for this deployed in 1.5.0-beta2. Long story short something in Electron 1.1.1 is causing the require('electron').screen to fail and until I have more time to investigate I rolled back to 1.1.0.
