### ISSUE TITLE
Themes tab does not open

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/wp-desktop#235]
### Expected behavior

I expect the Themes tab to open when I go to My Sites > Themes, with "Themes" highlighted in the sidebar.

### Actual behavior

The first time I click on "Themes" in the sidebar after opening the app, it opens but "Themes" is not highlighted in the sidebar (instead, the last tab I was on is still highlighted):

![screen shot 2016-09-08 at 2 23 27 pm](https://cloud.githubusercontent.com/assets/8658164/18350913/fd50fd54-75cf-11e6-8208-ae7ab31f8774.png)

However, the Themes tab only works the first time. If I navigate away and click on it again, the tab doesn't open. (If I close the app and reopen it, though, it will open with the Themes tab open.)

I confirmed that this is only an issue in the app (not in a browser). There are no console errors when I click the "Themes" tab, but once it starts being unresponsive, when I click away from the Themes tab to a different tab I get this console error:

> build.js:43 (node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.

##### Tested on Mac OSX 10.11.6, WP Desktop app version 1.7.0-beta1

**Comment by rachelmcr** [comment]
I just updated to version 1.8.0-beta1 and this continues to be an issue there.

**Comment by folletto** [comment]
For reference, might be related to https://github.com/Automattic/wp-calypso/issues/7530 (which has been fixed yesterday)

**Comment by seear** [comment]
#7530 does not fix this issue.

For some reason, the [un-mounting middleware](https://github.com/Automattic/wp-calypso/blob/3a43d9d43c0e1fb2c15472d6c5be87beaddfc892/client/boot/index.js#L407), which is necessary for laying out the _themes_ section properly, is not firing on Desktop. In fact, any middleware hooked up after the [`sections.load()` call](https://github.com/Automattic/wp-calypso/blob/3a43d9d43c0e1fb2c15472d6c5be87beaddfc892/client/boot/index.js#L315) is not firing on Desktop.

**Comment by seear** [comment]
Further to this, the un-mounter middleware has to be hooked up after the `sections.load()` call, because there is middleware hooked up in `sections.load()` that sets section name to state, which the un-mounter uses.

So we can't do a temp fix by moving the un-mounter `page()` call above `sections.load()`.

**Comment by seear** [comment]
This is caused by a misplaced `require` statement in the code loader. Fix in https://github.com/Automattic/wp-calypso/pull/8010

**Comment by seear** [comment]
Verified fixed in 1.8.0

<img width="848" alt="screen shot 2016-09-30 at 11 24 08" src="https://cloud.githubusercontent.com/assets/7767559/18988875/b763aca0-8700-11e6-904f-ddfec867cea2.png">
