### ISSUE TITLE
My Sites: My Sites and Editor don't load for some users, lots of JS errors

### ISSUE THREAD

**Issue by macmanx2** [Automattic/wp-desktop#258]
After selecting My Sites in the 2.1.0 version of the Mac app, either no sites load, or just a few sites load.

If just a few sites load, I can select one, but it doesn't really do anything more than highlight it.

I can confirm that I do not have this issue at WordPress.com itself under Firefox 50.1.0 and Chrome 55.0.2883.95.

Here is screenshot of the issue, including the JavaScript errors from the console:

<img width="1013" alt="screen shot 2017-01-03 at 3 10 40 pm" src="https://cloud.githubusercontent.com/assets/4856235/21626718/971f2f7a-d1c7-11e6-9327-e3e5cc24b3da.png">

**Comment by rachelmcr** [comment]
I reproduced the console errors above with slightly different behavior in the UI. Instead of getting stuck on the site picker, when I selected My Sites I got another Reader view but with text overlapping in the sidebar. This happens in the beta version 2.2.0-beta1.

However, this only happens to me when I am logged in to one account. Logged in to other accounts, the My Sites tab loads normally.

**Comment by zandyring** [comment]
I was able to reproduce both of these, in 2.1.0 version. I initially saw the behavior Rachel describes:
![screen shot 2017-01-04 at 1 14 07 pm](https://cloud.githubusercontent.com/assets/7304712/21653939/754f5220-d281-11e6-92a0-37383a30fecc.png)

And after logging out and back in, I saw what James describes:
![screen shot 2017-01-04 at 1 23 26 pm](https://cloud.githubusercontent.com/assets/7304712/21653955/820e3ab2-d281-11e6-9579-592b3003f888.png)

**Comment by lancewillett** [comment]
@macmanx2 Can you test with a non-a8c user? Seems to only happen to folks when they are logging in as an Automattician.

**Comment by lancewillett** [comment]
Also both @macmanx2 @zandyring can you update to 2.2.0-beta1 and try to replicate the bug again?

**Comment by zandyring** [comment]
@lancewillett can confirm this happens for me in 2.2.0-beta1 while logged in as super admin. It happens when I have the toggle set to "unproxy" or "use system proxy". It doesn't happen for me in the 2.2.0-beta1 v when using a non-SA account.

**Comment by lancewillett** [comment]
Thanks for the info, @zandyring — that narrows it down to users with certain proxy settings, which explains how I wasn't able to repeat (I have that off).

**Comment by macmanx2** [comment]
My toggle has always been set to No Proxy, and I am still experiencing the issue under my Automattician user.

My normal user is not experiencing the issue.

**Comment by rachelmcr** [comment]
We now have several user reports of this issue, not just Automatticians:
https://github.com/Automattic/wp-desktop/issues/259
https://en.forums.wordpress.com/topic/app-will-no-longer-connnect-to-my-wordpresscom-account
p4a5px-1u2-p2

**Comment by aduth** [comment]
This should now be resolved. There appear to be cases where Jetpack sites will report to have a site icon configured but our API is unable to generate a URL for the corresponding media. The error was caused by an attempt to parse a `false` return value of `wp_get_attachment_image_url` as a URL. Even omitting these properties was not enough, since older versions of the Calypso client (prior to https://github.com/Automattic/wp-calypso/pull/10016) would infer the presence of an `icon` property meaning that a URL exists, which in the aforementioned sites is not true.

As of now, you can see the erroneous logic in https://github.com/Automattic/jetpack/pull/6025, which will need to be updated with the "fix". However, the immediate fix is to omit the `icon` property altogether if neither an `img` or `ico` property can be generated. This is not ideal if we know a site icon option exists and could be included, but is necessary because of assumptions made by legacy clients.

Future considerations include:

- Include `icon.media_id` if we know it, even if we can't generate `icon.img` or `icon.ico`
- Determine why we cannot generate the URL for some media on Jetpack sites

r148916-wpcom
r148914-wpcom

**Comment by aduth** [comment]
Also, one more important note: Because of sites caching in the client, the first attempt to revisit My Sites may still fail, but after fresh data has been received from the API, it should succeed thereafter.

**Comment by kr3t3n** [comment]
@aduth , the problem persists on my desktop. I have installed the latest suggested update today but the same behaviour leads to the same problem. I still cannot access my websites and can only use the app as a reader.

**Comment by aduth** [comment]
Hi @kr3t3n : Could you provide more details, including your current operating system and version and the WordPress application version, found under Help > About WordPress.com (Windows) or WordPress.com > About WordPress.com (Mac).

As noted in my previous comment, a stubborn cache may also be to blame. This should clear itself up automatically, perhaps requiring a reload of the application. A more thorough clear can be performed with the following instructions:

1. Press Ctrl-Shift-I (capital i)
2. Click the "Console" tab
3. Enter: `localStorage.clear(); indexedDB.deleteDatabase( 'calypso' );`
4. Press Enter
5. Restart application

Since the original issue is suspected to be caused by stale or invalid data through connected sites running the Jetpack plugin, it may also be worth trying to disconnect and reconnect these sites (using the Disconnect Jetpack option from the bottom of your site's `/wp-admin` Jetpack screen).

If issues persist after following these steps, we may need more information about your account and connected sites, which you can provide through our [support contact form](https://wordpress.com/help/contact).

**Comment by kr3t3n** [comment]
@aduth I'm using version 2.2.0 on laptop running Windows 10 Pro, this is what I get when trying the Console instruction:
http://imgur.com/a/VE5Q0

The problem persists.

**Comment by aduth** [comment]
@kr3t3n Can you provide information about your site(s) using our [support contact form](https://wordpress.com/help/contact) referencing this issue so we can try to isolate the problem? Or your WordPress.com account name here if you're comfortable sharing it in this public repository?

>A more thorough clear can be performed with the following instructions:

A more _more_ thorough clear you might try is reinstalling the application, though understandably an extreme approach than I'd typically want to suggest.

**Comment by kr3t3n** [comment]
@aduth I re-installed and it worked! I'm amazed as I re-installed several times since initially reporting the problem. Now I can see my sites! Should I submit feedback and suggestions for improvement and new features? In GitHub or via the WordPress support?

**Comment by aduth** [comment]
Glad to hear it's working now @kr3t3n , though unfortunate it came to the extent of reinstalling the application. Since there was in-fact a bug at the time of the original issue being opened, it's quite possible that your earliest attempts at reinstalling were during the time where the bug was still present.

To your point on providing feedback, our support folks will be able to direct your suggestions most effectively to the relevant teams, though feel free to open an issue here or in the repository for the [underlying Calypso application](https://github.com/Automattic/wp-calypso).
